language: java

jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - openssl aes-256-cbc -K $encrypted_17183e73b8fd_key -iv $encrypted_17183e73b8fd_iv -in travis.tar.enc -out travis.tar -d
  - tar xvf travis.tar
  - cp travisres/config-test.properties src/test/resources/
  - mysql -e 'CREATE DATABASE filrouge_test;'
  - mysql filrouge_test < init-script.sql
  - mysql filrouge_test < src/test/resources/test-script.sql

script:
  - mvn package

after_success:
  - ./travisres/deploy.sh

cache:
  directories:
    - $HOME/.m2/repository